// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: management.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailablePaymentMethodsResponse struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	Response                *RPCResponse              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	AvailablePaymentMethods []*AvailablePaymentMethod `protobuf:"bytes,2,rep,name=availablePaymentMethods,proto3" json:"availablePaymentMethods,omitempty"`
	JsonStr                 string                    `protobuf:"bytes,3,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetAvailablePaymentMethodsResponse) Reset() {
	*x = GetAvailablePaymentMethodsResponse{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailablePaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailablePaymentMethodsResponse) ProtoMessage() {}

func (x *GetAvailablePaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailablePaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailablePaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailablePaymentMethodsResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetAvailablePaymentMethodsResponse) GetAvailablePaymentMethods() []*AvailablePaymentMethod {
	if x != nil {
		return x.AvailablePaymentMethods
	}
	return nil
}

func (x *GetAvailablePaymentMethodsResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type AvailablePaymentMethod struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Bank           *AvailablePaymentMethodBank `protobuf:"bytes,1,opt,name=bank,proto3" json:"bank,omitempty"`
	PicturePath    string                      `protobuf:"bytes,2,opt,name=picturePath,proto3" json:"picturePath,omitempty"`
	PaymentMethods []*PaymentMethods           `protobuf:"bytes,3,rep,name=paymentMethods,proto3" json:"paymentMethods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvailablePaymentMethod) Reset() {
	*x = AvailablePaymentMethod{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablePaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablePaymentMethod) ProtoMessage() {}

func (x *AvailablePaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablePaymentMethod.ProtoReflect.Descriptor instead.
func (*AvailablePaymentMethod) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *AvailablePaymentMethod) GetBank() *AvailablePaymentMethodBank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *AvailablePaymentMethod) GetPicturePath() string {
	if x != nil {
		return x.PicturePath
	}
	return ""
}

func (x *AvailablePaymentMethod) GetPaymentMethods() []*PaymentMethods {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

type AvailablePaymentMethodBank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SwiftCode     string                 `protobuf:"bytes,3,opt,name=swiftCode,proto3" json:"swiftCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablePaymentMethodBank) Reset() {
	*x = AvailablePaymentMethodBank{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablePaymentMethodBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablePaymentMethodBank) ProtoMessage() {}

func (x *AvailablePaymentMethodBank) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablePaymentMethodBank.ProtoReflect.Descriptor instead.
func (*AvailablePaymentMethodBank) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *AvailablePaymentMethodBank) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvailablePaymentMethodBank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailablePaymentMethodBank) GetSwiftCode() string {
	if x != nil {
		return x.SwiftCode
	}
	return ""
}

type PaymentMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentMethod *SnapHelper            `protobuf:"bytes,2,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethods) Reset() {
	*x = PaymentMethods{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethods) ProtoMessage() {}

func (x *PaymentMethods) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethods.ProtoReflect.Descriptor instead.
func (*PaymentMethods) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentMethods) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentMethods) GetPaymentMethod() *SnapHelper {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

type GetAvailableExternalBanksResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Response               *RPCResponse             `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	AvailableExternalBanks []*AvailableExternalBank `protobuf:"bytes,2,rep,name=availableExternalBanks,proto3" json:"availableExternalBanks,omitempty"`
	JsonStr                string                   `protobuf:"bytes,3,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAvailableExternalBanksResponse) Reset() {
	*x = GetAvailableExternalBanksResponse{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableExternalBanksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableExternalBanksResponse) ProtoMessage() {}

func (x *GetAvailableExternalBanksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableExternalBanksResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableExternalBanksResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvailableExternalBanksResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetAvailableExternalBanksResponse) GetAvailableExternalBanks() []*AvailableExternalBank {
	if x != nil {
		return x.AvailableExternalBanks
	}
	return nil
}

func (x *GetAvailableExternalBanksResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type AvailableExternalBank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SwiftCode     string                 `protobuf:"bytes,2,opt,name=swiftCode,proto3" json:"swiftCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableExternalBank) Reset() {
	*x = AvailableExternalBank{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableExternalBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableExternalBank) ProtoMessage() {}

func (x *AvailableExternalBank) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableExternalBank.ProtoReflect.Descriptor instead.
func (*AvailableExternalBank) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *AvailableExternalBank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailableExternalBank) GetSwiftCode() string {
	if x != nil {
		return x.SwiftCode
	}
	return ""
}

type GetBankSwiftCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankName      string                 `protobuf:"bytes,1,opt,name=bankName,proto3" json:"bankName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankSwiftCodeRequest) Reset() {
	*x = GetBankSwiftCodeRequest{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankSwiftCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankSwiftCodeRequest) ProtoMessage() {}

func (x *GetBankSwiftCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankSwiftCodeRequest.ProtoReflect.Descriptor instead.
func (*GetBankSwiftCodeRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *GetBankSwiftCodeRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type GetBankSwiftCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	BankName      string                 `protobuf:"bytes,2,opt,name=bankName,proto3" json:"bankName,omitempty"`
	SwiftCode     string                 `protobuf:"bytes,3,opt,name=swiftCode,proto3" json:"swiftCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankSwiftCodeResponse) Reset() {
	*x = GetBankSwiftCodeResponse{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankSwiftCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankSwiftCodeResponse) ProtoMessage() {}

func (x *GetBankSwiftCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankSwiftCodeResponse.ProtoReflect.Descriptor instead.
func (*GetBankSwiftCodeResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *GetBankSwiftCodeResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetBankSwiftCodeResponse) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *GetBankSwiftCodeResponse) GetSwiftCode() string {
	if x != nil {
		return x.SwiftCode
	}
	return ""
}

type GetPaymentMethodTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          []*SnapHelper          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodTypeResponse) Reset() {
	*x = GetPaymentMethodTypeResponse{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodTypeResponse) ProtoMessage() {}

func (x *GetPaymentMethodTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodTypeResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentMethodTypeResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetPaymentMethodTypeResponse) GetData() []*SnapHelper {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\apayment\x1a\n" +
	"snap.proto\"\xcb\x01\n" +
	"\"GetAvailablePaymentMethodsResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12Y\n" +
	"\x17availablePaymentMethods\x18\x02 \x03(\v2\x1f.payment.AvailablePaymentMethodR\x17availablePaymentMethods\x12\x18\n" +
	"\ajsonStr\x18\x03 \x01(\tR\ajsonStr\"\xb4\x01\n" +
	"\x16AvailablePaymentMethod\x127\n" +
	"\x04bank\x18\x01 \x01(\v2#.payment.AvailablePaymentMethodBankR\x04bank\x12 \n" +
	"\vpicturePath\x18\x02 \x01(\tR\vpicturePath\x12?\n" +
	"\x0epaymentMethods\x18\x03 \x03(\v2\x17.payment.PaymentMethodsR\x0epaymentMethods\"^\n" +
	"\x1aAvailablePaymentMethodBank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tswiftCode\x18\x03 \x01(\tR\tswiftCode\"[\n" +
	"\x0ePaymentMethods\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\rpaymentMethod\x18\x02 \x01(\v2\x13.payment.SnapHelperR\rpaymentMethod\"\xc7\x01\n" +
	"!GetAvailableExternalBanksResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12V\n" +
	"\x16availableExternalBanks\x18\x02 \x03(\v2\x1e.payment.AvailableExternalBankR\x16availableExternalBanks\x12\x18\n" +
	"\ajsonStr\x18\x03 \x01(\tR\ajsonStr\"I\n" +
	"\x15AvailableExternalBank\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tswiftCode\x18\x02 \x01(\tR\tswiftCode\"5\n" +
	"\x17GetBankSwiftCodeRequest\x12\x1a\n" +
	"\bbankName\x18\x01 \x01(\tR\bbankName\"\x86\x01\n" +
	"\x18GetBankSwiftCodeResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12\x1a\n" +
	"\bbankName\x18\x02 \x01(\tR\bbankName\x12\x1c\n" +
	"\tswiftCode\x18\x03 \x01(\tR\tswiftCode\"y\n" +
	"\x1cGetPaymentMethodTypeResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.payment.SnapHelperR\x04data2\xef\x02\n" +
	"\x11ManagementService\x12Y\n" +
	"\x1aGetAvailablePaymentMethods\x12\x0e.payment.Empty\x1a+.payment.GetAvailablePaymentMethodsResponse\x12W\n" +
	"\x19GetAvailableExternalBanks\x12\x0e.payment.Empty\x1a*.payment.GetAvailableExternalBanksResponse\x12W\n" +
	"\x10GetBankSwiftCode\x12 .payment.GetBankSwiftCodeRequest\x1a!.payment.GetBankSwiftCodeResponse\x12M\n" +
	"\x14GetPaymentMethodType\x12\x0e.payment.Empty\x1a%.payment.GetPaymentMethodTypeResponseB\x04Z\x02./b\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_management_proto_goTypes = []any{
	(*GetAvailablePaymentMethodsResponse)(nil), // 0: payment.GetAvailablePaymentMethodsResponse
	(*AvailablePaymentMethod)(nil),             // 1: payment.AvailablePaymentMethod
	(*AvailablePaymentMethodBank)(nil),         // 2: payment.AvailablePaymentMethodBank
	(*PaymentMethods)(nil),                     // 3: payment.PaymentMethods
	(*GetAvailableExternalBanksResponse)(nil),  // 4: payment.GetAvailableExternalBanksResponse
	(*AvailableExternalBank)(nil),              // 5: payment.AvailableExternalBank
	(*GetBankSwiftCodeRequest)(nil),            // 6: payment.GetBankSwiftCodeRequest
	(*GetBankSwiftCodeResponse)(nil),           // 7: payment.GetBankSwiftCodeResponse
	(*GetPaymentMethodTypeResponse)(nil),       // 8: payment.GetPaymentMethodTypeResponse
	(*RPCResponse)(nil),                        // 9: payment.RPCResponse
	(*SnapHelper)(nil),                         // 10: payment.SnapHelper
	(*Empty)(nil),                              // 11: payment.Empty
}
var file_management_proto_depIdxs = []int32{
	9,  // 0: payment.GetAvailablePaymentMethodsResponse.response:type_name -> payment.RPCResponse
	1,  // 1: payment.GetAvailablePaymentMethodsResponse.availablePaymentMethods:type_name -> payment.AvailablePaymentMethod
	2,  // 2: payment.AvailablePaymentMethod.bank:type_name -> payment.AvailablePaymentMethodBank
	3,  // 3: payment.AvailablePaymentMethod.paymentMethods:type_name -> payment.PaymentMethods
	10, // 4: payment.PaymentMethods.paymentMethod:type_name -> payment.SnapHelper
	9,  // 5: payment.GetAvailableExternalBanksResponse.response:type_name -> payment.RPCResponse
	5,  // 6: payment.GetAvailableExternalBanksResponse.availableExternalBanks:type_name -> payment.AvailableExternalBank
	9,  // 7: payment.GetBankSwiftCodeResponse.response:type_name -> payment.RPCResponse
	9,  // 8: payment.GetPaymentMethodTypeResponse.response:type_name -> payment.RPCResponse
	10, // 9: payment.GetPaymentMethodTypeResponse.data:type_name -> payment.SnapHelper
	11, // 10: payment.ManagementService.GetAvailablePaymentMethods:input_type -> payment.Empty
	11, // 11: payment.ManagementService.GetAvailableExternalBanks:input_type -> payment.Empty
	6,  // 12: payment.ManagementService.GetBankSwiftCode:input_type -> payment.GetBankSwiftCodeRequest
	11, // 13: payment.ManagementService.GetPaymentMethodType:input_type -> payment.Empty
	0,  // 14: payment.ManagementService.GetAvailablePaymentMethods:output_type -> payment.GetAvailablePaymentMethodsResponse
	4,  // 15: payment.ManagementService.GetAvailableExternalBanks:output_type -> payment.GetAvailableExternalBanksResponse
	7,  // 16: payment.ManagementService.GetBankSwiftCode:output_type -> payment.GetBankSwiftCodeResponse
	8,  // 17: payment.ManagementService.GetPaymentMethodType:output_type -> payment.GetPaymentMethodTypeResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	file_snap_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
