// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: payment-gateway.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVirtualAccountInfoRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TransactionIdentifier string                 `protobuf:"bytes,1,opt,name=transactionIdentifier,proto3" json:"transactionIdentifier,omitempty"`
	IdBank                int32                  `protobuf:"varint,2,opt,name=idBank,proto3" json:"idBank,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetVirtualAccountInfoRequest) Reset() {
	*x = GetVirtualAccountInfoRequest{}
	mi := &file_payment_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualAccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualAccountInfoRequest) ProtoMessage() {}

func (x *GetVirtualAccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualAccountInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVirtualAccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_payment_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetVirtualAccountInfoRequest) GetTransactionIdentifier() string {
	if x != nil {
		return x.TransactionIdentifier
	}
	return ""
}

func (x *GetVirtualAccountInfoRequest) GetIdBank() int32 {
	if x != nil {
		return x.IdBank
	}
	return 0
}

type GetVirtualAccountInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	VaData        *VirtualAccountData    `protobuf:"bytes,2,opt,name=vaData,proto3" json:"vaData,omitempty"`
	JsonStr       string                 `protobuf:"bytes,3,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVirtualAccountInfoResponse) Reset() {
	*x = GetVirtualAccountInfoResponse{}
	mi := &file_payment_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualAccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualAccountInfoResponse) ProtoMessage() {}

func (x *GetVirtualAccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualAccountInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVirtualAccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_payment_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetVirtualAccountInfoResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVirtualAccountInfoResponse) GetVaData() *VirtualAccountData {
	if x != nil {
		return x.VaData
	}
	return nil
}

func (x *GetVirtualAccountInfoResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type VirtualAccountData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppInfo            *SnapHelper            `protobuf:"bytes,1,opt,name=appInfo,proto3" json:"appInfo,omitempty"`
	BankInfo           *BankInfo              `protobuf:"bytes,2,opt,name=bankInfo,proto3" json:"bankInfo,omitempty"`
	Id                 string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Status             *SnapHelper            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AppReference       *AppReference          `protobuf:"bytes,5,opt,name=appReference,proto3" json:"appReference,omitempty"`
	ExpireDate         string                 `protobuf:"bytes,6,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	VirtualAccountNo   string                 `protobuf:"bytes,7,opt,name=virtualAccountNo,proto3" json:"virtualAccountNo,omitempty"`
	VirtualAccountName string                 `protobuf:"bytes,8,opt,name=virtualAccountName,proto3" json:"virtualAccountName,omitempty"`
	TotalAmount        *BalanceAmount         `protobuf:"bytes,9,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	FeeAmount          *BalanceAmount         `protobuf:"bytes,10,opt,name=feeAmount,proto3" json:"feeAmount,omitempty"`
	PaidAmount         *BalanceAmount         `protobuf:"bytes,11,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	CreateAt           string                 `protobuf:"bytes,12,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt           string                 `protobuf:"bytes,13,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VirtualAccountData) Reset() {
	*x = VirtualAccountData{}
	mi := &file_payment_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualAccountData) ProtoMessage() {}

func (x *VirtualAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualAccountData.ProtoReflect.Descriptor instead.
func (*VirtualAccountData) Descriptor() ([]byte, []int) {
	return file_payment_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualAccountData) GetAppInfo() *SnapHelper {
	if x != nil {
		return x.AppInfo
	}
	return nil
}

func (x *VirtualAccountData) GetBankInfo() *BankInfo {
	if x != nil {
		return x.BankInfo
	}
	return nil
}

func (x *VirtualAccountData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VirtualAccountData) GetStatus() *SnapHelper {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VirtualAccountData) GetAppReference() *AppReference {
	if x != nil {
		return x.AppReference
	}
	return nil
}

func (x *VirtualAccountData) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *VirtualAccountData) GetVirtualAccountNo() string {
	if x != nil {
		return x.VirtualAccountNo
	}
	return ""
}

func (x *VirtualAccountData) GetVirtualAccountName() string {
	if x != nil {
		return x.VirtualAccountName
	}
	return ""
}

func (x *VirtualAccountData) GetTotalAmount() *BalanceAmount {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *VirtualAccountData) GetFeeAmount() *BalanceAmount {
	if x != nil {
		return x.FeeAmount
	}
	return nil
}

func (x *VirtualAccountData) GetPaidAmount() *BalanceAmount {
	if x != nil {
		return x.PaidAmount
	}
	return nil
}

func (x *VirtualAccountData) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *VirtualAccountData) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type AppReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrxId         int64                  `protobuf:"varint,1,opt,name=trxId,proto3" json:"trxId,omitempty"`
	TrxIdentifier string                 `protobuf:"bytes,2,opt,name=trxIdentifier,proto3" json:"trxIdentifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppReference) Reset() {
	*x = AppReference{}
	mi := &file_payment_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReference) ProtoMessage() {}

func (x *AppReference) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReference.ProtoReflect.Descriptor instead.
func (*AppReference) Descriptor() ([]byte, []int) {
	return file_payment_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AppReference) GetTrxId() int64 {
	if x != nil {
		return x.TrxId
	}
	return 0
}

func (x *AppReference) GetTrxIdentifier() string {
	if x != nil {
		return x.TrxIdentifier
	}
	return ""
}

type BankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PicturePath   string                 `protobuf:"bytes,3,opt,name=picturePath,proto3" json:"picturePath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankInfo) Reset() {
	*x = BankInfo{}
	mi := &file_payment_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankInfo) ProtoMessage() {}

func (x *BankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankInfo.ProtoReflect.Descriptor instead.
func (*BankInfo) Descriptor() ([]byte, []int) {
	return file_payment_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *BankInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BankInfo) GetPicturePath() string {
	if x != nil {
		return x.PicturePath
	}
	return ""
}

var File_payment_gateway_proto protoreflect.FileDescriptor

const file_payment_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15payment-gateway.proto\x12\apayment\x1a\n" +
	"snap.proto\"l\n" +
	"\x1cGetVirtualAccountInfoRequest\x124\n" +
	"\x15transactionIdentifier\x18\x01 \x01(\tR\x15transactionIdentifier\x12\x16\n" +
	"\x06idBank\x18\x02 \x01(\x05R\x06idBank\"\xa0\x01\n" +
	"\x1dGetVirtualAccountInfoResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x123\n" +
	"\x06vaData\x18\x02 \x01(\v2\x1b.payment.VirtualAccountDataR\x06vaData\x12\x18\n" +
	"\ajsonStr\x18\x03 \x01(\tR\ajsonStr\"\xc6\x04\n" +
	"\x12VirtualAccountData\x12-\n" +
	"\aappInfo\x18\x01 \x01(\v2\x13.payment.SnapHelperR\aappInfo\x12-\n" +
	"\bbankInfo\x18\x02 \x01(\v2\x11.payment.BankInfoR\bbankInfo\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12+\n" +
	"\x06status\x18\x04 \x01(\v2\x13.payment.SnapHelperR\x06status\x129\n" +
	"\fappReference\x18\x05 \x01(\v2\x15.payment.AppReferenceR\fappReference\x12\x1e\n" +
	"\n" +
	"expireDate\x18\x06 \x01(\tR\n" +
	"expireDate\x12*\n" +
	"\x10virtualAccountNo\x18\a \x01(\tR\x10virtualAccountNo\x12.\n" +
	"\x12virtualAccountName\x18\b \x01(\tR\x12virtualAccountName\x128\n" +
	"\vtotalAmount\x18\t \x01(\v2\x16.payment.BalanceAmountR\vtotalAmount\x124\n" +
	"\tfeeAmount\x18\n" +
	" \x01(\v2\x16.payment.BalanceAmountR\tfeeAmount\x126\n" +
	"\n" +
	"paidAmount\x18\v \x01(\v2\x16.payment.BalanceAmountR\n" +
	"paidAmount\x12\x1a\n" +
	"\bcreateAt\x18\f \x01(\tR\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\r \x01(\tR\bupdateAt\"J\n" +
	"\fAppReference\x12\x14\n" +
	"\x05trxId\x18\x01 \x01(\x03R\x05trxId\x12$\n" +
	"\rtrxIdentifier\x18\x02 \x01(\tR\rtrxIdentifier\"P\n" +
	"\bBankInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpicturePath\x18\x03 \x01(\tR\vpicturePath2\xf2\x01\n" +
	"\x15PaymentGatewayService\x12f\n" +
	"\x15GetVirtualAccountInfo\x12%.payment.GetVirtualAccountInfoRequest\x1a&.payment.GetVirtualAccountInfoResponse\x123\n" +
	"\x11GetPartneredBanks\x12\x0e.payment.Empty\x1a\x0e.payment.Empty\x12<\n" +
	"\x1aGetAvailablePaymentMethods\x12\x0e.payment.Empty\x1a\x0e.payment.EmptyB\x04Z\x02./b\x06proto3"

var (
	file_payment_gateway_proto_rawDescOnce sync.Once
	file_payment_gateway_proto_rawDescData []byte
)

func file_payment_gateway_proto_rawDescGZIP() []byte {
	file_payment_gateway_proto_rawDescOnce.Do(func() {
		file_payment_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_gateway_proto_rawDesc), len(file_payment_gateway_proto_rawDesc)))
	})
	return file_payment_gateway_proto_rawDescData
}

var file_payment_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_gateway_proto_goTypes = []any{
	(*GetVirtualAccountInfoRequest)(nil),  // 0: payment.GetVirtualAccountInfoRequest
	(*GetVirtualAccountInfoResponse)(nil), // 1: payment.GetVirtualAccountInfoResponse
	(*VirtualAccountData)(nil),            // 2: payment.VirtualAccountData
	(*AppReference)(nil),                  // 3: payment.AppReference
	(*BankInfo)(nil),                      // 4: payment.BankInfo
	(*RPCResponse)(nil),                   // 5: payment.RPCResponse
	(*SnapHelper)(nil),                    // 6: payment.SnapHelper
	(*BalanceAmount)(nil),                 // 7: payment.BalanceAmount
	(*Empty)(nil),                         // 8: payment.Empty
}
var file_payment_gateway_proto_depIdxs = []int32{
	5,  // 0: payment.GetVirtualAccountInfoResponse.response:type_name -> payment.RPCResponse
	2,  // 1: payment.GetVirtualAccountInfoResponse.vaData:type_name -> payment.VirtualAccountData
	6,  // 2: payment.VirtualAccountData.appInfo:type_name -> payment.SnapHelper
	4,  // 3: payment.VirtualAccountData.bankInfo:type_name -> payment.BankInfo
	6,  // 4: payment.VirtualAccountData.status:type_name -> payment.SnapHelper
	3,  // 5: payment.VirtualAccountData.appReference:type_name -> payment.AppReference
	7,  // 6: payment.VirtualAccountData.totalAmount:type_name -> payment.BalanceAmount
	7,  // 7: payment.VirtualAccountData.feeAmount:type_name -> payment.BalanceAmount
	7,  // 8: payment.VirtualAccountData.paidAmount:type_name -> payment.BalanceAmount
	0,  // 9: payment.PaymentGatewayService.GetVirtualAccountInfo:input_type -> payment.GetVirtualAccountInfoRequest
	8,  // 10: payment.PaymentGatewayService.GetPartneredBanks:input_type -> payment.Empty
	8,  // 11: payment.PaymentGatewayService.GetAvailablePaymentMethods:input_type -> payment.Empty
	1,  // 12: payment.PaymentGatewayService.GetVirtualAccountInfo:output_type -> payment.GetVirtualAccountInfoResponse
	8,  // 13: payment.PaymentGatewayService.GetPartneredBanks:output_type -> payment.Empty
	8,  // 14: payment.PaymentGatewayService.GetAvailablePaymentMethods:output_type -> payment.Empty
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_payment_gateway_proto_init() }
func file_payment_gateway_proto_init() {
	if File_payment_gateway_proto != nil {
		return
	}
	file_snap_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_gateway_proto_rawDesc), len(file_payment_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_gateway_proto_goTypes,
		DependencyIndexes: file_payment_gateway_proto_depIdxs,
		MessageInfos:      file_payment_gateway_proto_msgTypes,
	}.Build()
	File_payment_gateway_proto = out.File
	file_payment_gateway_proto_goTypes = nil
	file_payment_gateway_proto_depIdxs = nil
}
