/**
 * @fileoverview gRPC-Web generated client stub for payment
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: management.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var snap_pb = require('./snap_pb.js')
const proto = {};
proto.payment = require('./management_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.payment.ManagementServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.payment.ManagementServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.payment.Empty,
 *   !proto.payment.GetAvailablePaymentMethodsResponse>}
 */
const methodDescriptor_ManagementService_GetAvailablePaymentMethods = new grpc.web.MethodDescriptor(
  '/payment.ManagementService/GetAvailablePaymentMethods',
  grpc.web.MethodType.UNARY,
  snap_pb.Empty,
  proto.payment.GetAvailablePaymentMethodsResponse,
  /**
   * @param {!proto.payment.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.payment.GetAvailablePaymentMethodsResponse.deserializeBinary
);


/**
 * @param {!proto.payment.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.payment.GetAvailablePaymentMethodsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.payment.GetAvailablePaymentMethodsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.payment.ManagementServiceClient.prototype.getAvailablePaymentMethods =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/payment.ManagementService/GetAvailablePaymentMethods',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetAvailablePaymentMethods,
      callback);
};


/**
 * @param {!proto.payment.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.payment.GetAvailablePaymentMethodsResponse>}
 *     Promise that resolves to the response
 */
proto.payment.ManagementServicePromiseClient.prototype.getAvailablePaymentMethods =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/payment.ManagementService/GetAvailablePaymentMethods',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetAvailablePaymentMethods);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.payment.Empty,
 *   !proto.payment.GetAvailableExternalBanksResponse>}
 */
const methodDescriptor_ManagementService_GetAvailableExternalBanks = new grpc.web.MethodDescriptor(
  '/payment.ManagementService/GetAvailableExternalBanks',
  grpc.web.MethodType.UNARY,
  snap_pb.Empty,
  proto.payment.GetAvailableExternalBanksResponse,
  /**
   * @param {!proto.payment.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.payment.GetAvailableExternalBanksResponse.deserializeBinary
);


/**
 * @param {!proto.payment.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.payment.GetAvailableExternalBanksResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.payment.GetAvailableExternalBanksResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.payment.ManagementServiceClient.prototype.getAvailableExternalBanks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/payment.ManagementService/GetAvailableExternalBanks',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetAvailableExternalBanks,
      callback);
};


/**
 * @param {!proto.payment.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.payment.GetAvailableExternalBanksResponse>}
 *     Promise that resolves to the response
 */
proto.payment.ManagementServicePromiseClient.prototype.getAvailableExternalBanks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/payment.ManagementService/GetAvailableExternalBanks',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetAvailableExternalBanks);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.payment.GetBankSwiftCodeRequest,
 *   !proto.payment.GetBankSwiftCodeResponse>}
 */
const methodDescriptor_ManagementService_GetBankSwiftCode = new grpc.web.MethodDescriptor(
  '/payment.ManagementService/GetBankSwiftCode',
  grpc.web.MethodType.UNARY,
  proto.payment.GetBankSwiftCodeRequest,
  proto.payment.GetBankSwiftCodeResponse,
  /**
   * @param {!proto.payment.GetBankSwiftCodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.payment.GetBankSwiftCodeResponse.deserializeBinary
);


/**
 * @param {!proto.payment.GetBankSwiftCodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.payment.GetBankSwiftCodeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.payment.GetBankSwiftCodeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.payment.ManagementServiceClient.prototype.getBankSwiftCode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/payment.ManagementService/GetBankSwiftCode',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetBankSwiftCode,
      callback);
};


/**
 * @param {!proto.payment.GetBankSwiftCodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.payment.GetBankSwiftCodeResponse>}
 *     Promise that resolves to the response
 */
proto.payment.ManagementServicePromiseClient.prototype.getBankSwiftCode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/payment.ManagementService/GetBankSwiftCode',
      request,
      metadata || {},
      methodDescriptor_ManagementService_GetBankSwiftCode);
};


module.exports = proto.payment;

