// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: management.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_GetAvailablePaymentMethods_FullMethodName = "/payment.ManagementService/GetAvailablePaymentMethods"
	ManagementService_GetAvailableExternalBanks_FullMethodName  = "/payment.ManagementService/GetAvailableExternalBanks"
	ManagementService_GetBankSwiftCode_FullMethodName           = "/payment.ManagementService/GetBankSwiftCode"
	ManagementService_GetPaymentMethodType_FullMethodName       = "/payment.ManagementService/GetPaymentMethodType"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagementServiceClient interface {
	GetAvailablePaymentMethods(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsResponse, error)
	GetAvailableExternalBanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailableExternalBanksResponse, error)
	GetBankSwiftCode(ctx context.Context, in *GetBankSwiftCodeRequest, opts ...grpc.CallOption) (*GetBankSwiftCodeResponse, error)
	GetPaymentMethodType(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPaymentMethodTypeResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) GetAvailablePaymentMethods(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailablePaymentMethodsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAvailablePaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAvailableExternalBanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailableExternalBanksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableExternalBanksResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAvailableExternalBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetBankSwiftCode(ctx context.Context, in *GetBankSwiftCodeRequest, opts ...grpc.CallOption) (*GetBankSwiftCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankSwiftCodeResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetBankSwiftCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetPaymentMethodType(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPaymentMethodTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodTypeResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetPaymentMethodType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
type ManagementServiceServer interface {
	GetAvailablePaymentMethods(context.Context, *Empty) (*GetAvailablePaymentMethodsResponse, error)
	GetAvailableExternalBanks(context.Context, *Empty) (*GetAvailableExternalBanksResponse, error)
	GetBankSwiftCode(context.Context, *GetBankSwiftCodeRequest) (*GetBankSwiftCodeResponse, error)
	GetPaymentMethodType(context.Context, *Empty) (*GetPaymentMethodTypeResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) GetAvailablePaymentMethods(context.Context, *Empty) (*GetAvailablePaymentMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailablePaymentMethods not implemented")
}
func (UnimplementedManagementServiceServer) GetAvailableExternalBanks(context.Context, *Empty) (*GetAvailableExternalBanksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableExternalBanks not implemented")
}
func (UnimplementedManagementServiceServer) GetBankSwiftCode(context.Context, *GetBankSwiftCodeRequest) (*GetBankSwiftCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankSwiftCode not implemented")
}
func (UnimplementedManagementServiceServer) GetPaymentMethodType(context.Context, *Empty) (*GetPaymentMethodTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethodType not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_GetAvailablePaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAvailablePaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAvailablePaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAvailablePaymentMethods(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAvailableExternalBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAvailableExternalBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAvailableExternalBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAvailableExternalBanks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetBankSwiftCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankSwiftCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetBankSwiftCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetBankSwiftCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetBankSwiftCode(ctx, req.(*GetBankSwiftCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetPaymentMethodType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetPaymentMethodType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetPaymentMethodType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetPaymentMethodType(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailablePaymentMethods",
			Handler:    _ManagementService_GetAvailablePaymentMethods_Handler,
		},
		{
			MethodName: "GetAvailableExternalBanks",
			Handler:    _ManagementService_GetAvailableExternalBanks_Handler,
		},
		{
			MethodName: "GetBankSwiftCode",
			Handler:    _ManagementService_GetBankSwiftCode_Handler,
		},
		{
			MethodName: "GetPaymentMethodType",
			Handler:    _ManagementService_GetPaymentMethodType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
