// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: management.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagementServiceClient interface {
	GetAvailablePaymentMethods(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsResponse, error)
	GetAvailableExternalBanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailableExternalBanksResponse, error)
	GetBankSwiftCode(ctx context.Context, in *GetBankSwiftCodeRequest, opts ...grpc.CallOption) (*GetBankSwiftCodeResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) GetAvailablePaymentMethods(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsResponse, error) {
	out := new(GetAvailablePaymentMethodsResponse)
	err := c.cc.Invoke(ctx, "/payment.ManagementService/GetAvailablePaymentMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAvailableExternalBanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAvailableExternalBanksResponse, error) {
	out := new(GetAvailableExternalBanksResponse)
	err := c.cc.Invoke(ctx, "/payment.ManagementService/GetAvailableExternalBanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetBankSwiftCode(ctx context.Context, in *GetBankSwiftCodeRequest, opts ...grpc.CallOption) (*GetBankSwiftCodeResponse, error) {
	out := new(GetBankSwiftCodeResponse)
	err := c.cc.Invoke(ctx, "/payment.ManagementService/GetBankSwiftCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility
type ManagementServiceServer interface {
	GetAvailablePaymentMethods(context.Context, *Empty) (*GetAvailablePaymentMethodsResponse, error)
	GetAvailableExternalBanks(context.Context, *Empty) (*GetAvailableExternalBanksResponse, error)
	GetBankSwiftCode(context.Context, *GetBankSwiftCodeRequest) (*GetBankSwiftCodeResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedManagementServiceServer struct {
}

func (UnimplementedManagementServiceServer) GetAvailablePaymentMethods(context.Context, *Empty) (*GetAvailablePaymentMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailablePaymentMethods not implemented")
}
func (UnimplementedManagementServiceServer) GetAvailableExternalBanks(context.Context, *Empty) (*GetAvailableExternalBanksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableExternalBanks not implemented")
}
func (UnimplementedManagementServiceServer) GetBankSwiftCode(context.Context, *GetBankSwiftCodeRequest) (*GetBankSwiftCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankSwiftCode not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_GetAvailablePaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAvailablePaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.ManagementService/GetAvailablePaymentMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAvailablePaymentMethods(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAvailableExternalBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAvailableExternalBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.ManagementService/GetAvailableExternalBanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAvailableExternalBanks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetBankSwiftCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankSwiftCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetBankSwiftCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.ManagementService/GetBankSwiftCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetBankSwiftCode(ctx, req.(*GetBankSwiftCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailablePaymentMethods",
			Handler:    _ManagementService_GetAvailablePaymentMethods_Handler,
		},
		{
			MethodName: "GetAvailableExternalBanks",
			Handler:    _ManagementService_GetAvailableExternalBanks_Handler,
		},
		{
			MethodName: "GetBankSwiftCode",
			Handler:    _ManagementService_GetBankSwiftCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
