// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: snap.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_snap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{0}
}

func (x *RPCResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *RPCResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_snap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{1}
}

type AddVirtualAccountRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdTransaction         int64                  `protobuf:"varint,1,opt,name=idTransaction,proto3" json:"idTransaction,omitempty"`
	TransactionIdentifier string                 `protobuf:"bytes,2,opt,name=transactionIdentifier,proto3" json:"transactionIdentifier,omitempty"`
	IdBank                int64                  `protobuf:"varint,3,opt,name=idBank,proto3" json:"idBank,omitempty"`
	CustomerNo            string                 `protobuf:"bytes,4,opt,name=customerNo,proto3" json:"customerNo,omitempty"`
	AccountName           string                 `protobuf:"bytes,5,opt,name=accountName,proto3" json:"accountName,omitempty"`
	TotalAmount           string                 `protobuf:"bytes,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	FeeAmount             string                 `protobuf:"bytes,7,opt,name=feeAmount,proto3" json:"feeAmount,omitempty"`
	ExpireDate            string                 `protobuf:"bytes,8,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddVirtualAccountRequest) Reset() {
	*x = AddVirtualAccountRequest{}
	mi := &file_snap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVirtualAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVirtualAccountRequest) ProtoMessage() {}

func (x *AddVirtualAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVirtualAccountRequest.ProtoReflect.Descriptor instead.
func (*AddVirtualAccountRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{2}
}

func (x *AddVirtualAccountRequest) GetIdTransaction() int64 {
	if x != nil {
		return x.IdTransaction
	}
	return 0
}

func (x *AddVirtualAccountRequest) GetTransactionIdentifier() string {
	if x != nil {
		return x.TransactionIdentifier
	}
	return ""
}

func (x *AddVirtualAccountRequest) GetIdBank() int64 {
	if x != nil {
		return x.IdBank
	}
	return 0
}

func (x *AddVirtualAccountRequest) GetCustomerNo() string {
	if x != nil {
		return x.CustomerNo
	}
	return ""
}

func (x *AddVirtualAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AddVirtualAccountRequest) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *AddVirtualAccountRequest) GetFeeAmount() string {
	if x != nil {
		return x.FeeAmount
	}
	return ""
}

func (x *AddVirtualAccountRequest) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

type AddVirtualAccountResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Response              *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	VaNum                 string                 `protobuf:"bytes,2,opt,name=vaNum,proto3" json:"vaNum,omitempty"`
	ExpireDate            string                 `protobuf:"bytes,3,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	TransactionIdentifier string                 `protobuf:"bytes,4,opt,name=transactionIdentifier,proto3" json:"transactionIdentifier,omitempty"`
	BankInfo              *Bank                  `protobuf:"bytes,5,opt,name=bankInfo,proto3" json:"bankInfo,omitempty"`
	VaAccountName         string                 `protobuf:"bytes,6,opt,name=vaAccountName,proto3" json:"vaAccountName,omitempty"`
	TotalAmount           string                 `protobuf:"bytes,7,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Sample                []*RPCResponse         `protobuf:"bytes,8,rep,name=sample,proto3" json:"sample,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddVirtualAccountResponse) Reset() {
	*x = AddVirtualAccountResponse{}
	mi := &file_snap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVirtualAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVirtualAccountResponse) ProtoMessage() {}

func (x *AddVirtualAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVirtualAccountResponse.ProtoReflect.Descriptor instead.
func (*AddVirtualAccountResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{3}
}

func (x *AddVirtualAccountResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AddVirtualAccountResponse) GetVaNum() string {
	if x != nil {
		return x.VaNum
	}
	return ""
}

func (x *AddVirtualAccountResponse) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *AddVirtualAccountResponse) GetTransactionIdentifier() string {
	if x != nil {
		return x.TransactionIdentifier
	}
	return ""
}

func (x *AddVirtualAccountResponse) GetBankInfo() *Bank {
	if x != nil {
		return x.BankInfo
	}
	return nil
}

func (x *AddVirtualAccountResponse) GetVaAccountName() string {
	if x != nil {
		return x.VaAccountName
	}
	return ""
}

func (x *AddVirtualAccountResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *AddVirtualAccountResponse) GetSample() []*RPCResponse {
	if x != nil {
		return x.Sample
	}
	return nil
}

type BalanceInquiryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Response       *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	AccountNumber  string                 `protobuf:"bytes,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountName    string                 `protobuf:"bytes,3,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Balance        *BalanceAmount         `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceDetails *BalanceDetails        `protobuf:"bytes,5,opt,name=balanceDetails,proto3" json:"balanceDetails,omitempty"`
	JsonStr        string                 `protobuf:"bytes,6,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceInquiryResponse) Reset() {
	*x = BalanceInquiryResponse{}
	mi := &file_snap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceInquiryResponse) ProtoMessage() {}

func (x *BalanceInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceInquiryResponse.ProtoReflect.Descriptor instead.
func (*BalanceInquiryResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceInquiryResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BalanceInquiryResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BalanceInquiryResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BalanceInquiryResponse) GetBalance() *BalanceAmount {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *BalanceInquiryResponse) GetBalanceDetails() *BalanceDetails {
	if x != nil {
		return x.BalanceDetails
	}
	return nil
}

func (x *BalanceInquiryResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type BankStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDateTime  string                 `protobuf:"bytes,1,opt,name=fromDateTime,proto3" json:"fromDateTime,omitempty"`
	ToDateTime    string                 `protobuf:"bytes,2,opt,name=toDateTime,proto3" json:"toDateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankStatementRequest) Reset() {
	*x = BankStatementRequest{}
	mi := &file_snap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankStatementRequest) ProtoMessage() {}

func (x *BankStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankStatementRequest.ProtoReflect.Descriptor instead.
func (*BankStatementRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{5}
}

func (x *BankStatementRequest) GetFromDateTime() string {
	if x != nil {
		return x.FromDateTime
	}
	return ""
}

func (x *BankStatementRequest) GetToDateTime() string {
	if x != nil {
		return x.ToDateTime
	}
	return ""
}

type BankStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Balance       *BankStatementBalance  `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	CreditEntries *BankTransactionEntry  `protobuf:"bytes,3,opt,name=creditEntries,proto3" json:"creditEntries,omitempty"`
	DebitEntries  *BankTransactionEntry  `protobuf:"bytes,4,opt,name=debitEntries,proto3" json:"debitEntries,omitempty"`
	Statements    []*BankStatementDetail `protobuf:"bytes,5,rep,name=statements,proto3" json:"statements,omitempty"`
	JsonStr       string                 `protobuf:"bytes,6,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankStatementResponse) Reset() {
	*x = BankStatementResponse{}
	mi := &file_snap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankStatementResponse) ProtoMessage() {}

func (x *BankStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankStatementResponse.ProtoReflect.Descriptor instead.
func (*BankStatementResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{6}
}

func (x *BankStatementResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BankStatementResponse) GetBalance() *BankStatementBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *BankStatementResponse) GetCreditEntries() *BankTransactionEntry {
	if x != nil {
		return x.CreditEntries
	}
	return nil
}

func (x *BankStatementResponse) GetDebitEntries() *BankTransactionEntry {
	if x != nil {
		return x.DebitEntries
	}
	return nil
}

func (x *BankStatementResponse) GetStatements() []*BankStatementDetail {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *BankStatementResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type BankTransferRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Amount                 *BalanceAmount         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BeneficiaryAccountNo   string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	BeneficiaryAccountName string                 `protobuf:"bytes,3,opt,name=beneficiaryAccountName,proto3" json:"beneficiaryAccountName,omitempty"`
	BeneficiaryBankCode    string                 `protobuf:"bytes,4,opt,name=beneficiaryBankCode,proto3" json:"beneficiaryBankCode,omitempty"`
	BeneficiaryEmail       string                 `protobuf:"bytes,5,opt,name=beneficiaryEmail,proto3" json:"beneficiaryEmail,omitempty"`
	TransactionDate        string                 `protobuf:"bytes,6,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	TransactionRemark      string                 `protobuf:"bytes,7,opt,name=transactionRemark,proto3" json:"transactionRemark,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BankTransferRequest) Reset() {
	*x = BankTransferRequest{}
	mi := &file_snap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransferRequest) ProtoMessage() {}

func (x *BankTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransferRequest.ProtoReflect.Descriptor instead.
func (*BankTransferRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{7}
}

func (x *BankTransferRequest) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BankTransferRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *BankTransferRequest) GetBeneficiaryAccountName() string {
	if x != nil {
		return x.BeneficiaryAccountName
	}
	return ""
}

func (x *BankTransferRequest) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *BankTransferRequest) GetBeneficiaryEmail() string {
	if x != nil {
		return x.BeneficiaryEmail
	}
	return ""
}

func (x *BankTransferRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *BankTransferRequest) GetTransactionRemark() string {
	if x != nil {
		return x.TransactionRemark
	}
	return ""
}

type TransferIntraBankRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Amount                 *BalanceAmount         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BeneficiaryAccountNo   string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	BeneficiaryEmail       string                 `protobuf:"bytes,3,opt,name=beneficiaryEmail,proto3" json:"beneficiaryEmail,omitempty"`
	TransactionDate        string                 `protobuf:"bytes,4,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	BeneficiaryAccountName string                 `protobuf:"bytes,5,opt,name=beneficiaryAccountName,proto3" json:"beneficiaryAccountName,omitempty"`
	TransactionRemark      string                 `protobuf:"bytes,6,opt,name=transactionRemark,proto3" json:"transactionRemark,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransferIntraBankRequest) Reset() {
	*x = TransferIntraBankRequest{}
	mi := &file_snap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferIntraBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferIntraBankRequest) ProtoMessage() {}

func (x *TransferIntraBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferIntraBankRequest.ProtoReflect.Descriptor instead.
func (*TransferIntraBankRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{8}
}

func (x *TransferIntraBankRequest) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransferIntraBankRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *TransferIntraBankRequest) GetBeneficiaryEmail() string {
	if x != nil {
		return x.BeneficiaryEmail
	}
	return ""
}

func (x *TransferIntraBankRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *TransferIntraBankRequest) GetBeneficiaryAccountName() string {
	if x != nil {
		return x.BeneficiaryAccountName
	}
	return ""
}

func (x *TransferIntraBankRequest) GetTransactionRemark() string {
	if x != nil {
		return x.TransactionRemark
	}
	return ""
}

type TransferInterBankRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Amount                 *BalanceAmount         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BeneficiaryAccountNo   string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	BeneficiaryAccountName string                 `protobuf:"bytes,3,opt,name=beneficiaryAccountName,proto3" json:"beneficiaryAccountName,omitempty"`
	BeneficiaryBankCode    string                 `protobuf:"bytes,4,opt,name=beneficiaryBankCode,proto3" json:"beneficiaryBankCode,omitempty"`
	BeneficiaryEmail       string                 `protobuf:"bytes,5,opt,name=beneficiaryEmail,proto3" json:"beneficiaryEmail,omitempty"`
	TransactionDate        string                 `protobuf:"bytes,6,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	TransactionRemark      string                 `protobuf:"bytes,7,opt,name=transactionRemark,proto3" json:"transactionRemark,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransferInterBankRequest) Reset() {
	*x = TransferInterBankRequest{}
	mi := &file_snap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferInterBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInterBankRequest) ProtoMessage() {}

func (x *TransferInterBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInterBankRequest.ProtoReflect.Descriptor instead.
func (*TransferInterBankRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{9}
}

func (x *TransferInterBankRequest) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransferInterBankRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *TransferInterBankRequest) GetBeneficiaryAccountName() string {
	if x != nil {
		return x.BeneficiaryAccountName
	}
	return ""
}

func (x *TransferInterBankRequest) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *TransferInterBankRequest) GetBeneficiaryEmail() string {
	if x != nil {
		return x.BeneficiaryEmail
	}
	return ""
}

func (x *TransferInterBankRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *TransferInterBankRequest) GetTransactionRemark() string {
	if x != nil {
		return x.TransactionRemark
	}
	return ""
}

type BankTransferResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Response                      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	TransactionReferenceStr       string                 `protobuf:"bytes,2,opt,name=transactionReferenceStr,proto3" json:"transactionReferenceStr,omitempty"`
	ExternalId                    string                 `protobuf:"bytes,3,opt,name=externalId,proto3" json:"externalId,omitempty"`
	ServiceCode                   string                 `protobuf:"bytes,4,opt,name=serviceCode,proto3" json:"serviceCode,omitempty"`
	TransactionDate               string                 `protobuf:"bytes,5,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	JsonStr                       string                 `protobuf:"bytes,6,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	TransactionStatusCode         string                 `protobuf:"bytes,7,opt,name=transactionStatusCode,proto3" json:"transactionStatusCode,omitempty"`
	TransactionStatusDesc         string                 `protobuf:"bytes,8,opt,name=transactionStatusDesc,proto3" json:"transactionStatusDesc,omitempty"`
	TransactionStatusCodeInternal int32                  `protobuf:"varint,9,opt,name=transactionStatusCodeInternal,proto3" json:"transactionStatusCodeInternal,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *BankTransferResponse) Reset() {
	*x = BankTransferResponse{}
	mi := &file_snap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransferResponse) ProtoMessage() {}

func (x *BankTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransferResponse.ProtoReflect.Descriptor instead.
func (*BankTransferResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{10}
}

func (x *BankTransferResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BankTransferResponse) GetTransactionReferenceStr() string {
	if x != nil {
		return x.TransactionReferenceStr
	}
	return ""
}

func (x *BankTransferResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *BankTransferResponse) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *BankTransferResponse) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *BankTransferResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

func (x *BankTransferResponse) GetTransactionStatusCode() string {
	if x != nil {
		return x.TransactionStatusCode
	}
	return ""
}

func (x *BankTransferResponse) GetTransactionStatusDesc() string {
	if x != nil {
		return x.TransactionStatusDesc
	}
	return ""
}

func (x *BankTransferResponse) GetTransactionStatusCodeInternal() int32 {
	if x != nil {
		return x.TransactionStatusCodeInternal
	}
	return 0
}

type ExternalAccountInquiryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BeneficiaryBankCode  string                 `protobuf:"bytes,1,opt,name=beneficiaryBankCode,proto3" json:"beneficiaryBankCode,omitempty"`
	BeneficiaryAccountNo string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	InquiryService       string                 `protobuf:"bytes,3,opt,name=inquiryService,proto3" json:"inquiryService,omitempty"`
	PurposeCode          string                 `protobuf:"bytes,4,opt,name=purposeCode,proto3" json:"purposeCode,omitempty"`
	Amount               *BalanceAmount         `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExternalAccountInquiryRequest) Reset() {
	*x = ExternalAccountInquiryRequest{}
	mi := &file_snap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalAccountInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalAccountInquiryRequest) ProtoMessage() {}

func (x *ExternalAccountInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalAccountInquiryRequest.ProtoReflect.Descriptor instead.
func (*ExternalAccountInquiryRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{11}
}

func (x *ExternalAccountInquiryRequest) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *ExternalAccountInquiryRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *ExternalAccountInquiryRequest) GetInquiryService() string {
	if x != nil {
		return x.InquiryService
	}
	return ""
}

func (x *ExternalAccountInquiryRequest) GetPurposeCode() string {
	if x != nil {
		return x.PurposeCode
	}
	return ""
}

func (x *ExternalAccountInquiryRequest) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type ExternalAccountInquiryResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Response               *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	BeneficiaryAccountName string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountName,proto3" json:"beneficiaryAccountName,omitempty"`
	BeneficiaryAccountNo   string                 `protobuf:"bytes,3,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	BeneficiaryBankCode    string                 `protobuf:"bytes,4,opt,name=beneficiaryBankCode,proto3" json:"beneficiaryBankCode,omitempty"`
	JsonStr                string                 `protobuf:"bytes,5,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExternalAccountInquiryResponse) Reset() {
	*x = ExternalAccountInquiryResponse{}
	mi := &file_snap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalAccountInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalAccountInquiryResponse) ProtoMessage() {}

func (x *ExternalAccountInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalAccountInquiryResponse.ProtoReflect.Descriptor instead.
func (*ExternalAccountInquiryResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{12}
}

func (x *ExternalAccountInquiryResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExternalAccountInquiryResponse) GetBeneficiaryAccountName() string {
	if x != nil {
		return x.BeneficiaryAccountName
	}
	return ""
}

func (x *ExternalAccountInquiryResponse) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *ExternalAccountInquiryResponse) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *ExternalAccountInquiryResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type InternalAccountInquiryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BeneficiaryAccountNo string                 `protobuf:"bytes,1,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InternalAccountInquiryRequest) Reset() {
	*x = InternalAccountInquiryRequest{}
	mi := &file_snap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalAccountInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalAccountInquiryRequest) ProtoMessage() {}

func (x *InternalAccountInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalAccountInquiryRequest.ProtoReflect.Descriptor instead.
func (*InternalAccountInquiryRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{13}
}

func (x *InternalAccountInquiryRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

type InternalAccountInquiryResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Response               *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	BeneficiaryAccountName string                 `protobuf:"bytes,2,opt,name=beneficiaryAccountName,proto3" json:"beneficiaryAccountName,omitempty"`
	BeneficiaryAccountNo   string                 `protobuf:"bytes,3,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	JsonStr                string                 `protobuf:"bytes,4,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InternalAccountInquiryResponse) Reset() {
	*x = InternalAccountInquiryResponse{}
	mi := &file_snap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalAccountInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalAccountInquiryResponse) ProtoMessage() {}

func (x *InternalAccountInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalAccountInquiryResponse.ProtoReflect.Descriptor instead.
func (*InternalAccountInquiryResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{14}
}

func (x *InternalAccountInquiryResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *InternalAccountInquiryResponse) GetBeneficiaryAccountName() string {
	if x != nil {
		return x.BeneficiaryAccountName
	}
	return ""
}

func (x *InternalAccountInquiryResponse) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *InternalAccountInquiryResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type VirtualAccountStatusInquiryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaNum         string                 `protobuf:"bytes,1,opt,name=vaNum,proto3" json:"vaNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualAccountStatusInquiryRequest) Reset() {
	*x = VirtualAccountStatusInquiryRequest{}
	mi := &file_snap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualAccountStatusInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualAccountStatusInquiryRequest) ProtoMessage() {}

func (x *VirtualAccountStatusInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualAccountStatusInquiryRequest.ProtoReflect.Descriptor instead.
func (*VirtualAccountStatusInquiryRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{15}
}

func (x *VirtualAccountStatusInquiryRequest) GetVaNum() string {
	if x != nil {
		return x.VaNum
	}
	return ""
}

type VirtualAccountStatusInquiryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	VaNum         string                 `protobuf:"bytes,2,opt,name=vaNum,proto3" json:"vaNum,omitempty"`
	VaStatus      string                 `protobuf:"bytes,3,opt,name=vaStatus,proto3" json:"vaStatus,omitempty"`
	ExpireDate    string                 `protobuf:"bytes,4,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	PaidDate      string                 `protobuf:"bytes,5,opt,name=paidDate,proto3" json:"paidDate,omitempty"`
	JsonStr       string                 `protobuf:"bytes,6,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualAccountStatusInquiryResponse) Reset() {
	*x = VirtualAccountStatusInquiryResponse{}
	mi := &file_snap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualAccountStatusInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualAccountStatusInquiryResponse) ProtoMessage() {}

func (x *VirtualAccountStatusInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualAccountStatusInquiryResponse.ProtoReflect.Descriptor instead.
func (*VirtualAccountStatusInquiryResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{16}
}

func (x *VirtualAccountStatusInquiryResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *VirtualAccountStatusInquiryResponse) GetVaNum() string {
	if x != nil {
		return x.VaNum
	}
	return ""
}

func (x *VirtualAccountStatusInquiryResponse) GetVaStatus() string {
	if x != nil {
		return x.VaStatus
	}
	return ""
}

func (x *VirtualAccountStatusInquiryResponse) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *VirtualAccountStatusInquiryResponse) GetPaidDate() string {
	if x != nil {
		return x.PaidDate
	}
	return ""
}

func (x *VirtualAccountStatusInquiryResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type TransferStatusInquiryRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TransactionReferenceNo string                 `protobuf:"bytes,1,opt,name=transactionReferenceNo,proto3" json:"transactionReferenceNo,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransferStatusInquiryRequest) Reset() {
	*x = TransferStatusInquiryRequest{}
	mi := &file_snap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusInquiryRequest) ProtoMessage() {}

func (x *TransferStatusInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusInquiryRequest.ProtoReflect.Descriptor instead.
func (*TransferStatusInquiryRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{17}
}

func (x *TransferStatusInquiryRequest) GetTransactionReferenceNo() string {
	if x != nil {
		return x.TransactionReferenceNo
	}
	return ""
}

type TransferStatusInquiryResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Response                     *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ServiceTransactionReference  string                 `protobuf:"bytes,2,opt,name=serviceTransactionReference,proto3" json:"serviceTransactionReference,omitempty"`
	InternalTransactionReference string                 `protobuf:"bytes,3,opt,name=internalTransactionReference,proto3" json:"internalTransactionReference,omitempty"`
	ExternalId                   string                 `protobuf:"bytes,4,opt,name=externalId,proto3" json:"externalId,omitempty"`
	ServiceCode                  string                 `protobuf:"bytes,5,opt,name=serviceCode,proto3" json:"serviceCode,omitempty"`
	TransactionDate              string                 `protobuf:"bytes,6,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	Amount                       *BalanceAmount         `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	BeneficiaryAccountNo         string                 `protobuf:"bytes,8,opt,name=beneficiaryAccountNo,proto3" json:"beneficiaryAccountNo,omitempty"`
	BeneficiaryBankCode          string                 `protobuf:"bytes,9,opt,name=beneficiaryBankCode,proto3" json:"beneficiaryBankCode,omitempty"`
	TransactionStatusCode        string                 `protobuf:"bytes,10,opt,name=transactionStatusCode,proto3" json:"transactionStatusCode,omitempty"`
	TranscationStatusDesc        string                 `protobuf:"bytes,11,opt,name=transcationStatusDesc,proto3" json:"transcationStatusDesc,omitempty"`
	JsonStr                      string                 `protobuf:"bytes,12,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"` // JSON representation of the response
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TransferStatusInquiryResponse) Reset() {
	*x = TransferStatusInquiryResponse{}
	mi := &file_snap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusInquiryResponse) ProtoMessage() {}

func (x *TransferStatusInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusInquiryResponse.ProtoReflect.Descriptor instead.
func (*TransferStatusInquiryResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{18}
}

func (x *TransferStatusInquiryResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TransferStatusInquiryResponse) GetServiceTransactionReference() string {
	if x != nil {
		return x.ServiceTransactionReference
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetInternalTransactionReference() string {
	if x != nil {
		return x.InternalTransactionReference
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransferStatusInquiryResponse) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetTransactionStatusCode() string {
	if x != nil {
		return x.TransactionStatusCode
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetTranscationStatusDesc() string {
	if x != nil {
		return x.TranscationStatusDesc
	}
	return ""
}

func (x *TransferStatusInquiryResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type GenerateQRISRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdApp          int64                  `protobuf:"varint,1,opt,name=idApp,proto3" json:"idApp,omitempty"`
	AppReferenceNo string                 `protobuf:"bytes,2,opt,name=appReferenceNo,proto3" json:"appReferenceNo,omitempty"` // uuidv4
	Amount         *BalanceAmount         `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateQRISRequest) Reset() {
	*x = GenerateQRISRequest{}
	mi := &file_snap_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRISRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRISRequest) ProtoMessage() {}

func (x *GenerateQRISRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRISRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRISRequest) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateQRISRequest) GetIdApp() int64 {
	if x != nil {
		return x.IdApp
	}
	return 0
}

func (x *GenerateQRISRequest) GetAppReferenceNo() string {
	if x != nil {
		return x.AppReferenceNo
	}
	return ""
}

func (x *GenerateQRISRequest) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type GenerateQRISResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        *RPCResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	BankReferenceNo string                 `protobuf:"bytes,2,opt,name=bankReferenceNo,proto3" json:"bankReferenceNo,omitempty"`
	PgReferenceNo   string                 `protobuf:"bytes,3,opt,name=pgReferenceNo,proto3" json:"pgReferenceNo,omitempty"`
	AppReferenceNo  string                 `protobuf:"bytes,4,opt,name=appReferenceNo,proto3" json:"appReferenceNo,omitempty"`
	Qris            *QRIS                  `protobuf:"bytes,5,opt,name=qris,proto3" json:"qris,omitempty"`
	MerchantName    string                 `protobuf:"bytes,6,opt,name=merchantName,proto3" json:"merchantName,omitempty"`
	StoreId         string                 `protobuf:"bytes,7,opt,name=storeId,proto3" json:"storeId,omitempty"`
	TerminalId      string                 `protobuf:"bytes,8,opt,name=terminalId,proto3" json:"terminalId,omitempty"`
	JsonStr         string                 `protobuf:"bytes,12,opt,name=jsonStr,proto3" json:"jsonStr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateQRISResponse) Reset() {
	*x = GenerateQRISResponse{}
	mi := &file_snap_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRISResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRISResponse) ProtoMessage() {}

func (x *GenerateQRISResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRISResponse.ProtoReflect.Descriptor instead.
func (*GenerateQRISResponse) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateQRISResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GenerateQRISResponse) GetBankReferenceNo() string {
	if x != nil {
		return x.BankReferenceNo
	}
	return ""
}

func (x *GenerateQRISResponse) GetPgReferenceNo() string {
	if x != nil {
		return x.PgReferenceNo
	}
	return ""
}

func (x *GenerateQRISResponse) GetAppReferenceNo() string {
	if x != nil {
		return x.AppReferenceNo
	}
	return ""
}

func (x *GenerateQRISResponse) GetQris() *QRIS {
	if x != nil {
		return x.Qris
	}
	return nil
}

func (x *GenerateQRISResponse) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *GenerateQRISResponse) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GenerateQRISResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *GenerateQRISResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type BalanceAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	HintText      *HintText              `protobuf:"bytes,3,opt,name=hintText,proto3" json:"hintText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceAmount) Reset() {
	*x = BalanceAmount{}
	mi := &file_snap_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceAmount) ProtoMessage() {}

func (x *BalanceAmount) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceAmount.ProtoReflect.Descriptor instead.
func (*BalanceAmount) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{21}
}

func (x *BalanceAmount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BalanceAmount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BalanceAmount) GetHintText() *HintText {
	if x != nil {
		return x.HintText
	}
	return nil
}

type HintText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	En            string                 `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintText) Reset() {
	*x = HintText{}
	mi := &file_snap_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintText) ProtoMessage() {}

func (x *HintText) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintText.ProtoReflect.Descriptor instead.
func (*HintText) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{22}
}

func (x *HintText) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

func (x *HintText) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BalanceDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AvailableBalance *BalanceAmount         `protobuf:"bytes,1,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	FloatBalance     *BalanceAmount         `protobuf:"bytes,2,opt,name=floatBalance,proto3" json:"floatBalance,omitempty"`
	HoldBalance      *BalanceAmount         `protobuf:"bytes,3,opt,name=holdBalance,proto3" json:"holdBalance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceDetails) Reset() {
	*x = BalanceDetails{}
	mi := &file_snap_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetails) ProtoMessage() {}

func (x *BalanceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetails.ProtoReflect.Descriptor instead.
func (*BalanceDetails) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{23}
}

func (x *BalanceDetails) GetAvailableBalance() *BalanceAmount {
	if x != nil {
		return x.AvailableBalance
	}
	return nil
}

func (x *BalanceDetails) GetFloatBalance() *BalanceAmount {
	if x != nil {
		return x.FloatBalance
	}
	return nil
}

func (x *BalanceDetails) GetHoldBalance() *BalanceAmount {
	if x != nil {
		return x.HoldBalance
	}
	return nil
}

type BankStatementBalanceDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BalanceDetails *BalanceAmount         `protobuf:"bytes,1,opt,name=balanceDetails,proto3" json:"balanceDetails,omitempty"`
	DateTime       string                 `protobuf:"bytes,2,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BankStatementBalanceDetail) Reset() {
	*x = BankStatementBalanceDetail{}
	mi := &file_snap_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankStatementBalanceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankStatementBalanceDetail) ProtoMessage() {}

func (x *BankStatementBalanceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankStatementBalanceDetail.ProtoReflect.Descriptor instead.
func (*BankStatementBalanceDetail) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{24}
}

func (x *BankStatementBalanceDetail) GetBalanceDetails() *BalanceAmount {
	if x != nil {
		return x.BalanceDetails
	}
	return nil
}

func (x *BankStatementBalanceDetail) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

type BankStatementBalance struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Amount          *BankStatementBalanceDetail `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	StartingBalance *BankStatementBalanceDetail `protobuf:"bytes,2,opt,name=startingBalance,proto3" json:"startingBalance,omitempty"`
	EndingBalance   *BankStatementBalanceDetail `protobuf:"bytes,3,opt,name=endingBalance,proto3" json:"endingBalance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BankStatementBalance) Reset() {
	*x = BankStatementBalance{}
	mi := &file_snap_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankStatementBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankStatementBalance) ProtoMessage() {}

func (x *BankStatementBalance) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankStatementBalance.ProtoReflect.Descriptor instead.
func (*BankStatementBalance) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{25}
}

func (x *BankStatementBalance) GetAmount() *BankStatementBalanceDetail {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BankStatementBalance) GetStartingBalance() *BankStatementBalanceDetail {
	if x != nil {
		return x.StartingBalance
	}
	return nil
}

func (x *BankStatementBalance) GetEndingBalance() *BankStatementBalanceDetail {
	if x != nil {
		return x.EndingBalance
	}
	return nil
}

type BankTransactionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumOfEntries  string                 `protobuf:"bytes,1,opt,name=numOfEntries,proto3" json:"numOfEntries,omitempty"`
	Amount        *BalanceAmount         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankTransactionEntry) Reset() {
	*x = BankTransactionEntry{}
	mi := &file_snap_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransactionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransactionEntry) ProtoMessage() {}

func (x *BankTransactionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransactionEntry.ProtoReflect.Descriptor instead.
func (*BankTransactionEntry) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{26}
}

func (x *BankTransactionEntry) GetNumOfEntries() string {
	if x != nil {
		return x.NumOfEntries
	}
	return ""
}

func (x *BankTransactionEntry) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

type BankStatementDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Amount            *BalanceAmount         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType   string                 `protobuf:"bytes,2,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	TransactionRemark string                 `protobuf:"bytes,3,opt,name=transactionRemark,proto3" json:"transactionRemark,omitempty"`
	TransactionDate   string                 `protobuf:"bytes,4,opt,name=transactionDate,proto3" json:"transactionDate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BankStatementDetail) Reset() {
	*x = BankStatementDetail{}
	mi := &file_snap_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankStatementDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankStatementDetail) ProtoMessage() {}

func (x *BankStatementDetail) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankStatementDetail.ProtoReflect.Descriptor instead.
func (*BankStatementDetail) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{27}
}

func (x *BankStatementDetail) GetAmount() *BalanceAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BankStatementDetail) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *BankStatementDetail) GetTransactionRemark() string {
	if x != nil {
		return x.TransactionRemark
	}
	return ""
}

func (x *BankStatementDetail) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

type SnapHelper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapHelper) Reset() {
	*x = SnapHelper{}
	mi := &file_snap_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapHelper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapHelper) ProtoMessage() {}

func (x *SnapHelper) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapHelper.ProtoReflect.Descriptor instead.
func (*SnapHelper) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{28}
}

func (x *SnapHelper) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SnapHelper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Helper        *SnapHelper            `protobuf:"bytes,1,opt,name=helper,proto3" json:"helper,omitempty"`
	PicturePath   string                 `protobuf:"bytes,2,opt,name=picturePath,proto3" json:"picturePath,omitempty"`
	SwiftCode     string                 `protobuf:"bytes,3,opt,name=swiftCode,proto3" json:"swiftCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_snap_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{29}
}

func (x *Bank) GetHelper() *SnapHelper {
	if x != nil {
		return x.Helper
	}
	return nil
}

func (x *Bank) GetPicturePath() string {
	if x != nil {
		return x.PicturePath
	}
	return ""
}

func (x *Bank) GetSwiftCode() string {
	if x != nil {
		return x.SwiftCode
	}
	return ""
}

type QRIS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrContent     string                 `protobuf:"bytes,1,opt,name=qrContent,proto3" json:"qrContent,omitempty"`
	QrURL         string                 `protobuf:"bytes,2,opt,name=qrURL,proto3" json:"qrURL,omitempty"`
	QrImage       string                 `protobuf:"bytes,3,opt,name=qrImage,proto3" json:"qrImage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRIS) Reset() {
	*x = QRIS{}
	mi := &file_snap_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRIS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRIS) ProtoMessage() {}

func (x *QRIS) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRIS.ProtoReflect.Descriptor instead.
func (*QRIS) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{30}
}

func (x *QRIS) GetQrContent() string {
	if x != nil {
		return x.QrContent
	}
	return ""
}

func (x *QRIS) GetQrURL() string {
	if x != nil {
		return x.QrURL
	}
	return ""
}

func (x *QRIS) GetQrImage() string {
	if x != nil {
		return x.QrImage
	}
	return ""
}

// To Trigger Pull on other services
type EmptyV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyV2) Reset() {
	*x = EmptyV2{}
	mi := &file_snap_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyV2) ProtoMessage() {}

func (x *EmptyV2) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyV2.ProtoReflect.Descriptor instead.
func (*EmptyV2) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{31}
}

var File_snap_proto protoreflect.FileDescriptor

const file_snap_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"snap.proto\x12\apayment\"C\n" +
	"\vRPCResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"\xb0\x02\n" +
	"\x18AddVirtualAccountRequest\x12$\n" +
	"\ridTransaction\x18\x01 \x01(\x03R\ridTransaction\x124\n" +
	"\x15transactionIdentifier\x18\x02 \x01(\tR\x15transactionIdentifier\x12\x16\n" +
	"\x06idBank\x18\x03 \x01(\x03R\x06idBank\x12\x1e\n" +
	"\n" +
	"customerNo\x18\x04 \x01(\tR\n" +
	"customerNo\x12 \n" +
	"\vaccountName\x18\x05 \x01(\tR\vaccountName\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\tR\vtotalAmount\x12\x1c\n" +
	"\tfeeAmount\x18\a \x01(\tR\tfeeAmount\x12\x1e\n" +
	"\n" +
	"expireDate\x18\b \x01(\tR\n" +
	"expireDate\"\xda\x02\n" +
	"\x19AddVirtualAccountResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12\x14\n" +
	"\x05vaNum\x18\x02 \x01(\tR\x05vaNum\x12\x1e\n" +
	"\n" +
	"expireDate\x18\x03 \x01(\tR\n" +
	"expireDate\x124\n" +
	"\x15transactionIdentifier\x18\x04 \x01(\tR\x15transactionIdentifier\x12)\n" +
	"\bbankInfo\x18\x05 \x01(\v2\r.payment.BankR\bbankInfo\x12$\n" +
	"\rvaAccountName\x18\x06 \x01(\tR\rvaAccountName\x12 \n" +
	"\vtotalAmount\x18\a \x01(\tR\vtotalAmount\x12,\n" +
	"\x06sample\x18\b \x03(\v2\x14.payment.RPCResponseR\x06sample\"\x9f\x02\n" +
	"\x16BalanceInquiryResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\tR\raccountNumber\x12 \n" +
	"\vaccountName\x18\x03 \x01(\tR\vaccountName\x120\n" +
	"\abalance\x18\x04 \x01(\v2\x16.payment.BalanceAmountR\abalance\x12?\n" +
	"\x0ebalanceDetails\x18\x05 \x01(\v2\x17.payment.BalanceDetailsR\x0ebalanceDetails\x12\x18\n" +
	"\ajsonStr\x18\x06 \x01(\tR\ajsonStr\"Z\n" +
	"\x14BankStatementRequest\x12\"\n" +
	"\ffromDateTime\x18\x01 \x01(\tR\ffromDateTime\x12\x1e\n" +
	"\n" +
	"toDateTime\x18\x02 \x01(\tR\n" +
	"toDateTime\"\xe2\x02\n" +
	"\x15BankStatementResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x127\n" +
	"\abalance\x18\x02 \x01(\v2\x1d.payment.BankStatementBalanceR\abalance\x12C\n" +
	"\rcreditEntries\x18\x03 \x01(\v2\x1d.payment.BankTransactionEntryR\rcreditEntries\x12A\n" +
	"\fdebitEntries\x18\x04 \x01(\v2\x1d.payment.BankTransactionEntryR\fdebitEntries\x12<\n" +
	"\n" +
	"statements\x18\x05 \x03(\v2\x1c.payment.BankStatementDetailR\n" +
	"statements\x12\x18\n" +
	"\ajsonStr\x18\x06 \x01(\tR\ajsonStr\"\xe7\x02\n" +
	"\x13BankTransferRequest\x12.\n" +
	"\x06amount\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x06amount\x122\n" +
	"\x14beneficiaryAccountNo\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x126\n" +
	"\x16beneficiaryAccountName\x18\x03 \x01(\tR\x16beneficiaryAccountName\x120\n" +
	"\x13beneficiaryBankCode\x18\x04 \x01(\tR\x13beneficiaryBankCode\x12*\n" +
	"\x10beneficiaryEmail\x18\x05 \x01(\tR\x10beneficiaryEmail\x12(\n" +
	"\x0ftransactionDate\x18\x06 \x01(\tR\x0ftransactionDate\x12,\n" +
	"\x11transactionRemark\x18\a \x01(\tR\x11transactionRemark\"\xba\x02\n" +
	"\x18TransferIntraBankRequest\x12.\n" +
	"\x06amount\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x06amount\x122\n" +
	"\x14beneficiaryAccountNo\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x12*\n" +
	"\x10beneficiaryEmail\x18\x03 \x01(\tR\x10beneficiaryEmail\x12(\n" +
	"\x0ftransactionDate\x18\x04 \x01(\tR\x0ftransactionDate\x126\n" +
	"\x16beneficiaryAccountName\x18\x05 \x01(\tR\x16beneficiaryAccountName\x12,\n" +
	"\x11transactionRemark\x18\x06 \x01(\tR\x11transactionRemark\"\xec\x02\n" +
	"\x18TransferInterBankRequest\x12.\n" +
	"\x06amount\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x06amount\x122\n" +
	"\x14beneficiaryAccountNo\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x126\n" +
	"\x16beneficiaryAccountName\x18\x03 \x01(\tR\x16beneficiaryAccountName\x120\n" +
	"\x13beneficiaryBankCode\x18\x04 \x01(\tR\x13beneficiaryBankCode\x12*\n" +
	"\x10beneficiaryEmail\x18\x05 \x01(\tR\x10beneficiaryEmail\x12(\n" +
	"\x0ftransactionDate\x18\x06 \x01(\tR\x0ftransactionDate\x12,\n" +
	"\x11transactionRemark\x18\a \x01(\tR\x11transactionRemark\"\xba\x03\n" +
	"\x14BankTransferResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x128\n" +
	"\x17transactionReferenceStr\x18\x02 \x01(\tR\x17transactionReferenceStr\x12\x1e\n" +
	"\n" +
	"externalId\x18\x03 \x01(\tR\n" +
	"externalId\x12 \n" +
	"\vserviceCode\x18\x04 \x01(\tR\vserviceCode\x12(\n" +
	"\x0ftransactionDate\x18\x05 \x01(\tR\x0ftransactionDate\x12\x18\n" +
	"\ajsonStr\x18\x06 \x01(\tR\ajsonStr\x124\n" +
	"\x15transactionStatusCode\x18\a \x01(\tR\x15transactionStatusCode\x124\n" +
	"\x15transactionStatusDesc\x18\b \x01(\tR\x15transactionStatusDesc\x12D\n" +
	"\x1dtransactionStatusCodeInternal\x18\t \x01(\x05R\x1dtransactionStatusCodeInternal\"\xff\x01\n" +
	"\x1dExternalAccountInquiryRequest\x120\n" +
	"\x13beneficiaryBankCode\x18\x01 \x01(\tR\x13beneficiaryBankCode\x122\n" +
	"\x14beneficiaryAccountNo\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x12&\n" +
	"\x0einquiryService\x18\x03 \x01(\tR\x0einquiryService\x12 \n" +
	"\vpurposeCode\x18\x04 \x01(\tR\vpurposeCode\x12.\n" +
	"\x06amount\x18\x05 \x01(\v2\x16.payment.BalanceAmountR\x06amount\"\x8a\x02\n" +
	"\x1eExternalAccountInquiryResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x126\n" +
	"\x16beneficiaryAccountName\x18\x02 \x01(\tR\x16beneficiaryAccountName\x122\n" +
	"\x14beneficiaryAccountNo\x18\x03 \x01(\tR\x14beneficiaryAccountNo\x120\n" +
	"\x13beneficiaryBankCode\x18\x04 \x01(\tR\x13beneficiaryBankCode\x12\x18\n" +
	"\ajsonStr\x18\x05 \x01(\tR\ajsonStr\"S\n" +
	"\x1dInternalAccountInquiryRequest\x122\n" +
	"\x14beneficiaryAccountNo\x18\x01 \x01(\tR\x14beneficiaryAccountNo\"\xd8\x01\n" +
	"\x1eInternalAccountInquiryResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x126\n" +
	"\x16beneficiaryAccountName\x18\x02 \x01(\tR\x16beneficiaryAccountName\x122\n" +
	"\x14beneficiaryAccountNo\x18\x03 \x01(\tR\x14beneficiaryAccountNo\x12\x18\n" +
	"\ajsonStr\x18\x04 \x01(\tR\ajsonStr\":\n" +
	"\"VirtualAccountStatusInquiryRequest\x12\x14\n" +
	"\x05vaNum\x18\x01 \x01(\tR\x05vaNum\"\xdf\x01\n" +
	"#VirtualAccountStatusInquiryResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12\x14\n" +
	"\x05vaNum\x18\x02 \x01(\tR\x05vaNum\x12\x1a\n" +
	"\bvaStatus\x18\x03 \x01(\tR\bvaStatus\x12\x1e\n" +
	"\n" +
	"expireDate\x18\x04 \x01(\tR\n" +
	"expireDate\x12\x1a\n" +
	"\bpaidDate\x18\x05 \x01(\tR\bpaidDate\x12\x18\n" +
	"\ajsonStr\x18\x06 \x01(\tR\ajsonStr\"V\n" +
	"\x1cTransferStatusInquiryRequest\x126\n" +
	"\x16transactionReferenceNo\x18\x01 \x01(\tR\x16transactionReferenceNo\"\xdf\x04\n" +
	"\x1dTransferStatusInquiryResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12@\n" +
	"\x1bserviceTransactionReference\x18\x02 \x01(\tR\x1bserviceTransactionReference\x12B\n" +
	"\x1cinternalTransactionReference\x18\x03 \x01(\tR\x1cinternalTransactionReference\x12\x1e\n" +
	"\n" +
	"externalId\x18\x04 \x01(\tR\n" +
	"externalId\x12 \n" +
	"\vserviceCode\x18\x05 \x01(\tR\vserviceCode\x12(\n" +
	"\x0ftransactionDate\x18\x06 \x01(\tR\x0ftransactionDate\x12.\n" +
	"\x06amount\x18\a \x01(\v2\x16.payment.BalanceAmountR\x06amount\x122\n" +
	"\x14beneficiaryAccountNo\x18\b \x01(\tR\x14beneficiaryAccountNo\x120\n" +
	"\x13beneficiaryBankCode\x18\t \x01(\tR\x13beneficiaryBankCode\x124\n" +
	"\x15transactionStatusCode\x18\n" +
	" \x01(\tR\x15transactionStatusCode\x124\n" +
	"\x15transcationStatusDesc\x18\v \x01(\tR\x15transcationStatusDesc\x12\x18\n" +
	"\ajsonStr\x18\f \x01(\tR\ajsonStr\"\x83\x01\n" +
	"\x13GenerateQRISRequest\x12\x14\n" +
	"\x05idApp\x18\x01 \x01(\x03R\x05idApp\x12&\n" +
	"\x0eappReferenceNo\x18\x02 \x01(\tR\x0eappReferenceNo\x12.\n" +
	"\x06amount\x18\x03 \x01(\v2\x16.payment.BalanceAmountR\x06amount\"\xdb\x02\n" +
	"\x14GenerateQRISResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.payment.RPCResponseR\bresponse\x12(\n" +
	"\x0fbankReferenceNo\x18\x02 \x01(\tR\x0fbankReferenceNo\x12$\n" +
	"\rpgReferenceNo\x18\x03 \x01(\tR\rpgReferenceNo\x12&\n" +
	"\x0eappReferenceNo\x18\x04 \x01(\tR\x0eappReferenceNo\x12!\n" +
	"\x04qris\x18\x05 \x01(\v2\r.payment.QRISR\x04qris\x12\"\n" +
	"\fmerchantName\x18\x06 \x01(\tR\fmerchantName\x12\x18\n" +
	"\astoreId\x18\a \x01(\tR\astoreId\x12\x1e\n" +
	"\n" +
	"terminalId\x18\b \x01(\tR\n" +
	"terminalId\x12\x18\n" +
	"\ajsonStr\x18\f \x01(\tR\ajsonStr\"p\n" +
	"\rBalanceAmount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12-\n" +
	"\bhintText\x18\x03 \x01(\v2\x11.payment.HintTextR\bhintText\"*\n" +
	"\bHintText\x12\x0e\n" +
	"\x02en\x18\x01 \x01(\tR\x02en\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xca\x01\n" +
	"\x0eBalanceDetails\x12B\n" +
	"\x10availableBalance\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x10availableBalance\x12:\n" +
	"\ffloatBalance\x18\x02 \x01(\v2\x16.payment.BalanceAmountR\ffloatBalance\x128\n" +
	"\vholdBalance\x18\x03 \x01(\v2\x16.payment.BalanceAmountR\vholdBalance\"x\n" +
	"\x1aBankStatementBalanceDetail\x12>\n" +
	"\x0ebalanceDetails\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x0ebalanceDetails\x12\x1a\n" +
	"\bdateTime\x18\x02 \x01(\tR\bdateTime\"\xed\x01\n" +
	"\x14BankStatementBalance\x12;\n" +
	"\x06amount\x18\x01 \x01(\v2#.payment.BankStatementBalanceDetailR\x06amount\x12M\n" +
	"\x0fstartingBalance\x18\x02 \x01(\v2#.payment.BankStatementBalanceDetailR\x0fstartingBalance\x12I\n" +
	"\rendingBalance\x18\x03 \x01(\v2#.payment.BankStatementBalanceDetailR\rendingBalance\"j\n" +
	"\x14BankTransactionEntry\x12\"\n" +
	"\fnumOfEntries\x18\x01 \x01(\tR\fnumOfEntries\x12.\n" +
	"\x06amount\x18\x02 \x01(\v2\x16.payment.BalanceAmountR\x06amount\"\xc7\x01\n" +
	"\x13BankStatementDetail\x12.\n" +
	"\x06amount\x18\x01 \x01(\v2\x16.payment.BalanceAmountR\x06amount\x12(\n" +
	"\x0ftransactionType\x18\x02 \x01(\tR\x0ftransactionType\x12,\n" +
	"\x11transactionRemark\x18\x03 \x01(\tR\x11transactionRemark\x12(\n" +
	"\x0ftransactionDate\x18\x04 \x01(\tR\x0ftransactionDate\"0\n" +
	"\n" +
	"SnapHelper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"s\n" +
	"\x04Bank\x12+\n" +
	"\x06helper\x18\x01 \x01(\v2\x13.payment.SnapHelperR\x06helper\x12 \n" +
	"\vpicturePath\x18\x02 \x01(\tR\vpicturePath\x12\x1c\n" +
	"\tswiftCode\x18\x03 \x01(\tR\tswiftCode\"T\n" +
	"\x04QRIS\x12\x1c\n" +
	"\tqrContent\x18\x01 \x01(\tR\tqrContent\x12\x14\n" +
	"\x05qrURL\x18\x02 \x01(\tR\x05qrURL\x12\x18\n" +
	"\aqrImage\x18\x03 \x01(\tR\aqrImage\"\t\n" +
	"\aEmptyV22\xfc\a\n" +
	"\vSnapService\x12Z\n" +
	"\x11AddVirtualAccount\x12!.payment.AddVirtualAccountRequest\x1a\".payment.AddVirtualAccountResponse\x12A\n" +
	"\x0eBalanceInquiry\x12\x0e.payment.Empty\x1a\x1f.payment.BalanceInquiryResponse\x12N\n" +
	"\rBankStatement\x12\x1d.payment.BankStatementRequest\x1a\x1e.payment.BankStatementResponse\x12U\n" +
	"\x11TransferIntraBank\x12!.payment.TransferIntraBankRequest\x1a\x1d.payment.BankTransferResponse\x12U\n" +
	"\x11TransferInterBank\x12!.payment.TransferInterBankRequest\x1a\x1d.payment.BankTransferResponse\x12K\n" +
	"\fBankTransfer\x12\x1c.payment.BankTransferRequest\x1a\x1d.payment.BankTransferResponse\x12i\n" +
	"\x16ExternalAccountInquiry\x12&.payment.ExternalAccountInquiryRequest\x1a'.payment.ExternalAccountInquiryResponse\x12i\n" +
	"\x16InternalAccountInquiry\x12&.payment.InternalAccountInquiryRequest\x1a'.payment.InternalAccountInquiryResponse\x12x\n" +
	"\x1bVirtualAccountStatusInquiry\x12+.payment.VirtualAccountStatusInquiryRequest\x1a,.payment.VirtualAccountStatusInquiryResponse\x12f\n" +
	"\x15TransferStatusInquiry\x12%.payment.TransferStatusInquiryRequest\x1a&.payment.TransferStatusInquiryResponse\x12K\n" +
	"\fGenerateQRIS\x12\x1c.payment.GenerateQRISRequest\x1a\x1d.payment.GenerateQRISResponseB\x04Z\x02./b\x06proto3"

var (
	file_snap_proto_rawDescOnce sync.Once
	file_snap_proto_rawDescData []byte
)

func file_snap_proto_rawDescGZIP() []byte {
	file_snap_proto_rawDescOnce.Do(func() {
		file_snap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snap_proto_rawDesc), len(file_snap_proto_rawDesc)))
	})
	return file_snap_proto_rawDescData
}

var file_snap_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_snap_proto_goTypes = []any{
	(*RPCResponse)(nil),                         // 0: payment.RPCResponse
	(*Empty)(nil),                               // 1: payment.Empty
	(*AddVirtualAccountRequest)(nil),            // 2: payment.AddVirtualAccountRequest
	(*AddVirtualAccountResponse)(nil),           // 3: payment.AddVirtualAccountResponse
	(*BalanceInquiryResponse)(nil),              // 4: payment.BalanceInquiryResponse
	(*BankStatementRequest)(nil),                // 5: payment.BankStatementRequest
	(*BankStatementResponse)(nil),               // 6: payment.BankStatementResponse
	(*BankTransferRequest)(nil),                 // 7: payment.BankTransferRequest
	(*TransferIntraBankRequest)(nil),            // 8: payment.TransferIntraBankRequest
	(*TransferInterBankRequest)(nil),            // 9: payment.TransferInterBankRequest
	(*BankTransferResponse)(nil),                // 10: payment.BankTransferResponse
	(*ExternalAccountInquiryRequest)(nil),       // 11: payment.ExternalAccountInquiryRequest
	(*ExternalAccountInquiryResponse)(nil),      // 12: payment.ExternalAccountInquiryResponse
	(*InternalAccountInquiryRequest)(nil),       // 13: payment.InternalAccountInquiryRequest
	(*InternalAccountInquiryResponse)(nil),      // 14: payment.InternalAccountInquiryResponse
	(*VirtualAccountStatusInquiryRequest)(nil),  // 15: payment.VirtualAccountStatusInquiryRequest
	(*VirtualAccountStatusInquiryResponse)(nil), // 16: payment.VirtualAccountStatusInquiryResponse
	(*TransferStatusInquiryRequest)(nil),        // 17: payment.TransferStatusInquiryRequest
	(*TransferStatusInquiryResponse)(nil),       // 18: payment.TransferStatusInquiryResponse
	(*GenerateQRISRequest)(nil),                 // 19: payment.GenerateQRISRequest
	(*GenerateQRISResponse)(nil),                // 20: payment.GenerateQRISResponse
	(*BalanceAmount)(nil),                       // 21: payment.BalanceAmount
	(*HintText)(nil),                            // 22: payment.HintText
	(*BalanceDetails)(nil),                      // 23: payment.BalanceDetails
	(*BankStatementBalanceDetail)(nil),          // 24: payment.BankStatementBalanceDetail
	(*BankStatementBalance)(nil),                // 25: payment.BankStatementBalance
	(*BankTransactionEntry)(nil),                // 26: payment.BankTransactionEntry
	(*BankStatementDetail)(nil),                 // 27: payment.BankStatementDetail
	(*SnapHelper)(nil),                          // 28: payment.SnapHelper
	(*Bank)(nil),                                // 29: payment.Bank
	(*QRIS)(nil),                                // 30: payment.QRIS
	(*EmptyV2)(nil),                             // 31: payment.EmptyV2
}
var file_snap_proto_depIdxs = []int32{
	0,  // 0: payment.AddVirtualAccountResponse.response:type_name -> payment.RPCResponse
	29, // 1: payment.AddVirtualAccountResponse.bankInfo:type_name -> payment.Bank
	0,  // 2: payment.AddVirtualAccountResponse.sample:type_name -> payment.RPCResponse
	0,  // 3: payment.BalanceInquiryResponse.response:type_name -> payment.RPCResponse
	21, // 4: payment.BalanceInquiryResponse.balance:type_name -> payment.BalanceAmount
	23, // 5: payment.BalanceInquiryResponse.balanceDetails:type_name -> payment.BalanceDetails
	0,  // 6: payment.BankStatementResponse.response:type_name -> payment.RPCResponse
	25, // 7: payment.BankStatementResponse.balance:type_name -> payment.BankStatementBalance
	26, // 8: payment.BankStatementResponse.creditEntries:type_name -> payment.BankTransactionEntry
	26, // 9: payment.BankStatementResponse.debitEntries:type_name -> payment.BankTransactionEntry
	27, // 10: payment.BankStatementResponse.statements:type_name -> payment.BankStatementDetail
	21, // 11: payment.BankTransferRequest.amount:type_name -> payment.BalanceAmount
	21, // 12: payment.TransferIntraBankRequest.amount:type_name -> payment.BalanceAmount
	21, // 13: payment.TransferInterBankRequest.amount:type_name -> payment.BalanceAmount
	0,  // 14: payment.BankTransferResponse.response:type_name -> payment.RPCResponse
	21, // 15: payment.ExternalAccountInquiryRequest.amount:type_name -> payment.BalanceAmount
	0,  // 16: payment.ExternalAccountInquiryResponse.response:type_name -> payment.RPCResponse
	0,  // 17: payment.InternalAccountInquiryResponse.response:type_name -> payment.RPCResponse
	0,  // 18: payment.VirtualAccountStatusInquiryResponse.response:type_name -> payment.RPCResponse
	0,  // 19: payment.TransferStatusInquiryResponse.response:type_name -> payment.RPCResponse
	21, // 20: payment.TransferStatusInquiryResponse.amount:type_name -> payment.BalanceAmount
	21, // 21: payment.GenerateQRISRequest.amount:type_name -> payment.BalanceAmount
	0,  // 22: payment.GenerateQRISResponse.response:type_name -> payment.RPCResponse
	30, // 23: payment.GenerateQRISResponse.qris:type_name -> payment.QRIS
	22, // 24: payment.BalanceAmount.hintText:type_name -> payment.HintText
	21, // 25: payment.BalanceDetails.availableBalance:type_name -> payment.BalanceAmount
	21, // 26: payment.BalanceDetails.floatBalance:type_name -> payment.BalanceAmount
	21, // 27: payment.BalanceDetails.holdBalance:type_name -> payment.BalanceAmount
	21, // 28: payment.BankStatementBalanceDetail.balanceDetails:type_name -> payment.BalanceAmount
	24, // 29: payment.BankStatementBalance.amount:type_name -> payment.BankStatementBalanceDetail
	24, // 30: payment.BankStatementBalance.startingBalance:type_name -> payment.BankStatementBalanceDetail
	24, // 31: payment.BankStatementBalance.endingBalance:type_name -> payment.BankStatementBalanceDetail
	21, // 32: payment.BankTransactionEntry.amount:type_name -> payment.BalanceAmount
	21, // 33: payment.BankStatementDetail.amount:type_name -> payment.BalanceAmount
	28, // 34: payment.Bank.helper:type_name -> payment.SnapHelper
	2,  // 35: payment.SnapService.AddVirtualAccount:input_type -> payment.AddVirtualAccountRequest
	1,  // 36: payment.SnapService.BalanceInquiry:input_type -> payment.Empty
	5,  // 37: payment.SnapService.BankStatement:input_type -> payment.BankStatementRequest
	8,  // 38: payment.SnapService.TransferIntraBank:input_type -> payment.TransferIntraBankRequest
	9,  // 39: payment.SnapService.TransferInterBank:input_type -> payment.TransferInterBankRequest
	7,  // 40: payment.SnapService.BankTransfer:input_type -> payment.BankTransferRequest
	11, // 41: payment.SnapService.ExternalAccountInquiry:input_type -> payment.ExternalAccountInquiryRequest
	13, // 42: payment.SnapService.InternalAccountInquiry:input_type -> payment.InternalAccountInquiryRequest
	15, // 43: payment.SnapService.VirtualAccountStatusInquiry:input_type -> payment.VirtualAccountStatusInquiryRequest
	17, // 44: payment.SnapService.TransferStatusInquiry:input_type -> payment.TransferStatusInquiryRequest
	19, // 45: payment.SnapService.GenerateQRIS:input_type -> payment.GenerateQRISRequest
	3,  // 46: payment.SnapService.AddVirtualAccount:output_type -> payment.AddVirtualAccountResponse
	4,  // 47: payment.SnapService.BalanceInquiry:output_type -> payment.BalanceInquiryResponse
	6,  // 48: payment.SnapService.BankStatement:output_type -> payment.BankStatementResponse
	10, // 49: payment.SnapService.TransferIntraBank:output_type -> payment.BankTransferResponse
	10, // 50: payment.SnapService.TransferInterBank:output_type -> payment.BankTransferResponse
	10, // 51: payment.SnapService.BankTransfer:output_type -> payment.BankTransferResponse
	12, // 52: payment.SnapService.ExternalAccountInquiry:output_type -> payment.ExternalAccountInquiryResponse
	14, // 53: payment.SnapService.InternalAccountInquiry:output_type -> payment.InternalAccountInquiryResponse
	16, // 54: payment.SnapService.VirtualAccountStatusInquiry:output_type -> payment.VirtualAccountStatusInquiryResponse
	18, // 55: payment.SnapService.TransferStatusInquiry:output_type -> payment.TransferStatusInquiryResponse
	20, // 56: payment.SnapService.GenerateQRIS:output_type -> payment.GenerateQRISResponse
	46, // [46:57] is the sub-list for method output_type
	35, // [35:46] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_snap_proto_init() }
func file_snap_proto_init() {
	if File_snap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snap_proto_rawDesc), len(file_snap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snap_proto_goTypes,
		DependencyIndexes: file_snap_proto_depIdxs,
		MessageInfos:      file_snap_proto_msgTypes,
	}.Build()
	File_snap_proto = out.File
	file_snap_proto_goTypes = nil
	file_snap_proto_depIdxs = nil
}
